apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bird
  namespace: kube-system
  labels:
    k8s-app: bird
spec:
  selector:
    matchLabels:
      name: bird
  template:
    metadata:
      labels:
        name: bird
    spec:
      containers:
      - name: bird
        image: rsmitty/bird
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        securityContext:
          privileged: true
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists